### PR TITLE
lib checked with eslint, added ES6 + fixed equity links flag

### PR DESCRIPTION
**Pull request by liesislukas**
added external_equity_links it was named same as external_links. Same name was also used for real external_links. Was not possible to get equity links with old version.

### CODE REVIEW

**Comment by scott-wyatt** [comment]
Wow, this is a huge update (thank you), and I'll admit it's been a bit since I've revisited this.  I'll merge and publish this, but i think we need to start writing tests if we are going to continue making updates and taking this to the next level.

**Comment by scott-wyatt** [comment]
okay, merged and published to NPM.

**Comment by liesislukas** [comment]
thanks for merge, also sent new pull request with actual eslint config for you and others to use. By the way, you should enable issue tracking for repository:

image

**Comment by scott-wyatt** [comment]
Excellent!  Issue tracking is now enabled.

**Pull request merged**
